[phases.setup]
cmds = [
  "cp /app/php-fpm.conf /assets/php-fpm.conf"
]

[start]
cmd = "php artisan storage:link --force && node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"
